<div class="container m-4 mt-8 p-2 bg-primary border border-secondary w-full md:w-1/2 hero">
    <img src="<?= $block->getViewFileUrl('images/banners/banner-hero.jpg') ?>" class="hero-banner" alt="hero"/>
</div>

<div class="h-64 hero">
    <div class="m-4 p-4 bg-green-600">
        <p2 class="text-2xl font-bold text-red">Wind-ecommerce</p>
    </div>
</div>

<div class="md:flex">
  <div class="md:flex-shrink-0">
    <img class="rounded-lg md:w-56" src="https://images.unsplash.com/photo-1580894908361-967195033215?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" alt="Woman paying for a purchase">
  </div>
  <div class="mt-4 md:mt-0 md:ml-6">
    <div class="uppercase tracking-wide text-sm text-indigo-600 font-bold">
      Marketing
    </div>
    <a href="/get-started" class="block mt-1 text-lg leading-tight font-semibold text-gray-900 hover:underline">
      Finding customers for your new business
    </a>
    <p class="mt-2 text-gray-600">
      Getting a new business off the ground is a lot of hard work.
      Here are five ideas you can use to find your first customers.
    </p>
  </div>
</div>
