<!doctype html>
<html <?= /* @noEscape */ $htmlAttributes ?>>
    <head <?= /* @noEscape */ $headAttributes ?>>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <?= /* @noEscape */ $headContent ?>
        <?= /* @noEscape */ $headAdditional ?>
    </head>
    <body data-container="body"
        <?= /* @noEscape */ $bodyAttributes ?>>
        <?= /* @noEscape */ $layoutContent ?>
        <script src="https://unpkg.com/alpinejs@3.0.0/dist/cdn.min.js" defer></script>
        <div x-data="{ open: false }">
            <button @click="open = !open">Toggle</button>

            <span x-show="open">
                Content...
            </span>
        </div>
    </body>
</html>
