<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$target = $block->getTarget();
$label = $block->getLabel();
$class = $block->getCssClass() ?? '';
?>
<a class="action <?= $class ?> skip <?= $block->escapeHtmlAttr($target) ?>"
   href="#<?= $block->escapeHtmlAttr($target) ?>">
    <span>
        <?= $block->escapeHtml($label) ?>
    </span>
</a>
